url: https://michellemccann.ca

siteTitle: Michelle McCann's Portfolio of Journalism

headerTitle: Michelle McCann

headerSubtitle: Portfolio of Writing & Journalism

navItems:
    - title: 'Top'
      url: '#'

    - title: 'Articles'
      url: '#articles'

    - title: 'About'
      url: '#about'

    - title: 'Contact'
      url: '#contact'
